File created on 02/05/2022, 21:26:05

[02/05/2022, 21:26:05 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ Error: Cannot find module './localModules/someFunctions'
[02/05/2022, 21:26:05 ERROR] (unknown): Require stack:
[02/05/2022, 21:26:05 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js
[02/05/2022, 21:26:05 ERROR] (unknown):     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/05/2022, 21:26:05 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/05/2022, 21:26:05 ERROR] (unknown):     at _allCode (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:96:13)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:34:1)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/05/2022, 21:26:05 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/05/2022, 21:26:05 ERROR] (unknown): 
[10/05/2022, 22:50:26 ERROR] (unknown): Uncaught Exception (process.on handle) Error: listen EADDRINUSE: address already in use :::1111
[10/05/2022, 22:50:26 ERROR] (unknown):     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[10/05/2022, 22:50:26 ERROR] (unknown):     at listenInCluster (net.js:1379:12)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Server.listen (net.js:1465:7)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Object.module.exports.start (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:92:10)
[10/05/2022, 22:50:26 ERROR] (unknown):     at _allCode (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:99:8)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Object.<anonymous> (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:34:1)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[10/05/2022, 22:50:26 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[10/05/2022, 22:50:26 ERROR] (unknown): 
[28/05/2022, 22:14:28 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\someFunctions.js:30
[28/05/2022, 22:14:28 ERROR] (unknown): module.exports.randInt = (min, max) {
[28/05/2022, 22:14:28 ERROR] (unknown):                                     ^
[28/05/2022, 22:14:28 ERROR] (unknown): 
[28/05/2022, 22:14:28 ERROR] (unknown): SyntaxError: Unexpected token '{'
[28/05/2022, 22:14:28 ERROR] (unknown):     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1049:27)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[28/05/2022, 22:14:28 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[28/05/2022, 22:14:28 ERROR] (unknown):     at _allCode (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:96:13)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:34:1)
[28/05/2022, 22:14:28 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[28/05/2022, 22:14:28 ERROR] (unknown): 
[02/06/2022, 20:23:55 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:23:55 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:23:55 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:23:55 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:23:55 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:23:55 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:23:55 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:23:55 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:23:55 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:23:55 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:23:55 ERROR] (unknown): 
[02/06/2022, 20:24:26 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:24:26 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:24:26 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:24:26 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:24:26 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:24:26 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:24:26 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:24:26 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:24:26 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:24:26 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:24:26 ERROR] (unknown): 
[02/06/2022, 20:24:36 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:24:36 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:24:36 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:24:36 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:24:36 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:24:36 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:24:36 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:24:36 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:24:36 ERROR] (unknown):     at Socket.<anonymous> (internal/child_process.js:443:11)
[02/06/2022, 20:24:36 ERROR] (unknown):     at Socket.emit (events.js:400:28)
[02/06/2022, 20:24:36 ERROR] (unknown):     at Pipe.<anonymous> (net.js:686:12)
[02/06/2022, 20:24:36 ERROR] (unknown): 
[02/06/2022, 20:25:08 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:25:08 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:25:08 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:25:08 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:25:08 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:25:08 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:25:08 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:25:08 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:25:08 ERROR] (unknown):     at Socket.<anonymous> (internal/child_process.js:443:11)
[02/06/2022, 20:25:08 ERROR] (unknown):     at Socket.emit (events.js:400:28)
[02/06/2022, 20:25:08 ERROR] (unknown):     at Pipe.<anonymous> (net.js:686:12)
[02/06/2022, 20:25:08 ERROR] (unknown): 
[02/06/2022, 20:28:39 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ TypeError: Speech is not a constructor
[02/06/2022, 20:28:39 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:8:16)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:28:39 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:20:16)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:28:39 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:28:39 ERROR] (unknown): 
[02/06/2022, 20:29:31 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ TypeError: Speech is not a function
[02/06/2022, 20:29:31 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:8:16)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:29:31 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:20:16)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:29:31 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:29:31 ERROR] (unknown): 
[02/06/2022, 20:29:39 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ TypeError: Speech.Speech is not a constructor
[02/06/2022, 20:29:39 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:8:16)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:29:39 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:20:16)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:29:39 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:29:39 ERROR] (unknown): 
[02/06/2022, 20:31:19 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\react-native-tts\index.js:1
[02/06/2022, 20:31:19 ERROR] (unknown): import { NativeModules, NativeEventEmitter, Platform } from 'react-native';
[02/06/2022, 20:31:19 ERROR] (unknown): ^^^^^^
[02/06/2022, 20:31:19 ERROR] (unknown): 
[02/06/2022, 20:31:19 ERROR] (unknown): SyntaxError: Cannot use import statement outside a module
[02/06/2022, 20:31:19 ERROR] (unknown):     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1049:27)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:31:19 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:8:11)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:31:19 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:31:19 ERROR] (unknown): 
[02/06/2022, 20:33:08 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:33:08 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:33:08 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:33:08 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:33:08 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:33:08 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:33:08 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:33:08 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:33:08 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:33:08 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:33:08 ERROR] (unknown): 
[02/06/2022, 20:33:29 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:33:29 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:33:29 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:33:29 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:33:29 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:18:6
[02/06/2022, 20:33:29 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:33:29 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:33:29 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:33:29 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:33:29 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:33:29 ERROR] (unknown): 
[02/06/2022, 20:34:35 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:34:35 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:34:35 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:34:35 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:34:35 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:17:6
[02/06/2022, 20:34:35 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:34:35 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:34:35 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:34:35 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:34:35 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:34:35 ERROR] (unknown): 
[02/06/2022, 20:34:57 ERROR] (unknown): Uncaught Exception (process.on handle) TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
[02/06/2022, 20:34:57 ERROR] (unknown):     at new NodeError (internal/errors.js:322:7)
[02/06/2022, 20:34:57 ERROR] (unknown):     at makeCallback (fs.js:176:11)
[02/06/2022, 20:34:57 ERROR] (unknown):     at Object.unlink (fs.js:1244:14)
[02/06/2022, 20:34:57 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\picotts\index.js:17:6
[02/06/2022, 20:34:57 ERROR] (unknown):     at ChildProcess.exithandler (child_process.js:390:5)
[02/06/2022, 20:34:57 ERROR] (unknown):     at ChildProcess.emit (events.js:400:28)
[02/06/2022, 20:34:57 ERROR] (unknown):     at maybeClose (internal/child_process.js:1058:16)
[02/06/2022, 20:34:57 ERROR] (unknown):     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[02/06/2022, 20:34:57 ERROR] (unknown):     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 20:34:57 ERROR] (unknown): 
[02/06/2022, 20:38:38 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:16
[02/06/2022, 20:38:38 ERROR] (unknown): let tts = (pond_list) => {
[02/06/2022, 20:38:38 ERROR] (unknown):     ^
[02/06/2022, 20:38:38 ERROR] (unknown): 
[02/06/2022, 20:38:38 ERROR] (unknown): SyntaxError: Identifier 'tts' has already been declared
[02/06/2022, 20:38:38 ERROR] (unknown):     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1049:27)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:38:38 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:20:16)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:38:38 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:38:38 ERROR] (unknown): 
[02/06/2022, 20:38:52 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ Error: Cannot find module 'talkify-tts'
[02/06/2022, 20:38:52 ERROR] (unknown): Require stack:
[02/06/2022, 20:38:52 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js
[02/06/2022, 20:38:52 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js
[02/06/2022, 20:38:52 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js
[02/06/2022, 20:38:52 ERROR] (unknown):     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:38:52 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:8:14)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:38:52 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:38:52 ERROR] (unknown): 
[02/06/2022, 20:59:28 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ ReferenceError: window is not defined
[02/06/2022, 20:59:28 ERROR] (unknown):     at TTS (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\node_modules\text-to-speech-offline\dist\index.js:3:21)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:15:1)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[02/06/2022, 20:59:28 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:20:16)
[02/06/2022, 20:59:28 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[02/06/2022, 20:59:28 ERROR] (unknown): 
[02/06/2022, 22:23:56 ERROR] (unknown): Uncaught Exception (process.on handle) Error: connect ETIMEDOUT 216.58.209.238:443
[02/06/2022, 22:23:56 ERROR] (unknown):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[02/06/2022, 22:23:56 ERROR] (unknown):     at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 22:23:56 ERROR] (unknown): 
[02/06/2022, 22:23:56 ERROR] (unknown): Uncaught Exception (process.on handle) Error: connect ETIMEDOUT 216.58.209.238:443
[02/06/2022, 22:23:56 ERROR] (unknown):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[02/06/2022, 22:23:56 ERROR] (unknown):     at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17)
[02/06/2022, 22:23:56 ERROR] (unknown): 
[03/06/2022, 16:16:35 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ Error: Cannot find module './node_modules/windows-tray/build/Release/tray'
[03/06/2022, 16:16:35 ERROR] (unknown): Require stack:
[03/06/2022, 16:16:35 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\windowsTrayMenu.js
[03/06/2022, 16:16:35 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js
[03/06/2022, 16:16:35 ERROR] (unknown):     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 16:16:35 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\windowsTrayMenu.js:6:18)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 16:16:35 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 16:16:35 ERROR] (unknown): 
[03/06/2022, 16:17:39 ERROR] (unknown): Uncaught Exception (process.on handle) Error: listen EADDRINUSE: address already in use :::1111
[03/06/2022, 16:17:39 ERROR] (unknown):     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[03/06/2022, 16:17:39 ERROR] (unknown):     at listenInCluster (net.js:1379:12)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Server.listen (net.js:1465:7)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Object.module.exports.start (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:118:10)
[03/06/2022, 16:17:39 ERROR] (unknown):     at _allCode (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:99:8)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Object.<anonymous> (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:33:1)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 16:17:39 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 16:17:39 ERROR] (unknown): 
[03/06/2022, 16:17:44 ERROR] (unknown): Uncaught Exception (process.on handle) Error: listen EADDRINUSE: address already in use :::1111
[03/06/2022, 16:17:44 ERROR] (unknown):     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[03/06/2022, 16:17:44 ERROR] (unknown):     at listenInCluster (net.js:1379:12)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Server.listen (net.js:1465:7)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Object.module.exports.start (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:118:10)
[03/06/2022, 16:17:44 ERROR] (unknown):     at _allCode (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:99:8)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Object.<anonymous> (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:33:1)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 16:17:44 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 16:17:44 ERROR] (unknown): 
[03/06/2022, 18:07:37 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ Error: Cannot find module './commands/computer_power_cmd'
[03/06/2022, 18:07:37 ERROR] (unknown): Require stack:
[03/06/2022, 18:07:37 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js
[03/06/2022, 18:07:37 ERROR] (unknown): - c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js
[03/06/2022, 18:07:37 ERROR] (unknown):     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[03/06/2022, 18:07:37 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[03/06/2022, 18:07:37 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 18:07:37 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 18:07:37 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:32:31
[03/06/2022, 18:07:37 ERROR] (unknown):     at Array.forEach (<anonymous>)
[03/06/2022, 18:07:37 ERROR] (unknown):     at getRequireListOfDirectory (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:26:26)
[03/06/2022, 18:07:37 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:60:25)
[03/06/2022, 18:07:37 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:164:22)
[03/06/2022, 18:07:37 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:07:37 ERROR] (unknown): 
[03/06/2022, 18:08:24 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ ReferenceError: Cannot access 'commandObject' before initialization
[03/06/2022, 18:08:24 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:33:27
[03/06/2022, 18:08:24 ERROR] (unknown):     at Array.forEach (<anonymous>)
[03/06/2022, 18:08:24 ERROR] (unknown):     at getRequireListOfDirectory (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:26:26)
[03/06/2022, 18:08:24 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:60:25)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:164:22)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 18:08:24 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 18:08:24 ERROR] (unknown): 
[03/06/2022, 18:08:29 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ ReferenceError: Cannot access 'commandObject' before initialization
[03/06/2022, 18:08:29 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:33:27
[03/06/2022, 18:08:29 ERROR] (unknown):     at Array.forEach (<anonymous>)
[03/06/2022, 18:08:29 ERROR] (unknown):     at getRequireListOfDirectory (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:26:26)
[03/06/2022, 18:08:29 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:60:25)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:164:22)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 18:08:29 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 18:08:29 ERROR] (unknown): 
[03/06/2022, 18:08:56 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ TypeError: list.push is not a function
[03/06/2022, 18:08:56 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:85:18
[03/06/2022, 18:08:56 ERROR] (unknown):     at Array.forEach (<anonymous>)
[03/06/2022, 18:08:56 ERROR] (unknown):     at getRequireListOfDirectory (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:76:26)
[03/06/2022, 18:08:56 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:110:25)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:214:22)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 18:08:56 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 18:08:56 ERROR] (unknown): 
[03/06/2022, 18:16:41 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ ReferenceError: Cannot access 'path' before initialization
[03/06/2022, 18:16:41 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\windowsTrayMenu.js:9:21)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 18:16:41 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 18:16:41 ERROR] (unknown):     at _allCode (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:98:1)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:33:1)
[03/06/2022, 18:16:41 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 18:16:41 ERROR] (unknown): 
[03/06/2022, 19:21:06 ERROR] (unknown): Unhandled Rejection (process.on handle) TypeError: Cannot read property 'exec' of undefined
[03/06/2022, 19:21:06 ERROR] (unknown):     at Object.function (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\brain\commands\computer_power_cmd.js:82:20)
[03/06/2022, 19:21:06 ERROR] (unknown):     at Timeout._onTimeout (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:76:41)
[03/06/2022, 19:21:06 ERROR] (unknown):     at listOnTimeout (internal/timers.js:557:17)
[03/06/2022, 19:21:06 ERROR] (unknown):     at processTimers (internal/timers.js:500:7)
[03/06/2022, 19:21:06 ERROR] (unknown): 
[03/06/2022, 19:21:57 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\brain\commands\computer_power_cmd.js:120
[03/06/2022, 19:21:57 ERROR] (unknown):             { weight: 1, value: "L'ordinateur redémarre" }
[03/06/2022, 19:21:57 ERROR] (unknown):             ^
[03/06/2022, 19:21:57 ERROR] (unknown): 
[03/06/2022, 19:21:57 ERROR] (unknown): SyntaxError: Unexpected token '{'
[03/06/2022, 19:21:57 ERROR] (unknown):     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
[03/06/2022, 19:21:57 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1049:27)
[03/06/2022, 19:21:57 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 19:21:57 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 19:21:57 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 19:21:57 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 19:21:57 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 19:21:57 ERROR] (unknown):     at c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:95:31
[03/06/2022, 19:21:57 ERROR] (unknown):     at Array.forEach (<anonymous>)
[03/06/2022, 19:21:57 ERROR] (unknown):     at getRequireListOfDirectory (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:89:26)
[03/06/2022, 19:21:57 ERROR] (unknown): 
[03/06/2022, 19:22:25 ERROR] (unknown): Unhandled Rejection (process.on handle) TypeError: Cannot read property 'exec' of undefined
[03/06/2022, 19:22:25 ERROR] (unknown):     at Object.function (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\brain\commands\computer_power_cmd.js:94:20)
[03/06/2022, 19:22:25 ERROR] (unknown):     at Timeout._onTimeout (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:76:41)
[03/06/2022, 19:22:25 ERROR] (unknown):     at listOnTimeout (internal/timers.js:557:17)
[03/06/2022, 19:22:25 ERROR] (unknown):     at processTimers (internal/timers.js:500:7)
[03/06/2022, 19:22:25 ERROR] (unknown): 
[03/06/2022, 19:23:58 ERROR] (unknown): Unhandled Rejection (process.on handle) TypeError: Cannot read property '_modules' of undefined
[03/06/2022, 19:23:58 ERROR] (unknown):     at Object.function (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\brain\commands\computer_power_cmd.js:94:20)
[03/06/2022, 19:23:58 ERROR] (unknown):     at Timeout._onTimeout (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:77:41)
[03/06/2022, 19:23:58 ERROR] (unknown):     at listOnTimeout (internal/timers.js:557:17)
[03/06/2022, 19:23:58 ERROR] (unknown):     at processTimers (internal/timers.js:500:7)
[03/06/2022, 19:23:58 ERROR] (unknown): 
[03/06/2022, 19:43:00 ERROR] (unknown): Unhandled Rejection (process.on handle) ReferenceError: Jar is not defined
[03/06/2022, 19:43:00 ERROR] (unknown):     at Timeout._onTimeout (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:77:42)
[03/06/2022, 19:43:00 ERROR] (unknown):     at listOnTimeout (internal/timers.js:557:17)
[03/06/2022, 19:43:00 ERROR] (unknown):     at processTimers (internal/timers.js:500:7)
[03/06/2022, 19:43:00 ERROR] (unknown): 
[03/06/2022, 21:50:18 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ TypeError: JarvisModules.actionManager is not a function
[03/06/2022, 21:50:18 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:147:45)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:293:22)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 21:50:18 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 21:50:18 ERROR] (unknown):     at _allCode (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:96:14)
[03/06/2022, 21:50:18 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:33:1)
[03/06/2022, 21:50:18 ERROR] (unknown): 
[03/06/2022, 21:54:18 ERROR] (unknown): /!\ UNCAUGH ERROR /!\ ReferenceError: args is not defined
[03/06/2022, 21:54:18 ERROR] (unknown):     at Object.debug (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:25:62)
[03/06/2022, 21:54:18 ERROR] (unknown):     at create_actionManager.testManager (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\brain\modules\actionManager.js:19:41)
[03/06/2022, 21:54:18 ERROR] (unknown):     at new createJarvis (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:150:29)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Object.<anonymous> (c:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:296:22)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 21:54:18 ERROR] (unknown):     at Module.require (internal/modules/cjs/loader.js:974:19)
[03/06/2022, 21:54:18 ERROR] (unknown):     at require (internal/modules/cjs/helpers.js:93:18)
[03/06/2022, 21:54:18 ERROR] (unknown): 
[03/06/2022, 22:02:59 ERROR] (unknown): Uncaught Exception (process.on handle) Error: listen EADDRINUSE: address already in use :::1111
[03/06/2022, 22:02:59 ERROR] (unknown):     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[03/06/2022, 22:02:59 ERROR] (unknown):     at listenInCluster (net.js:1379:12)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Server.listen (net.js:1465:7)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Object.module.exports.start (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\server.js:118:10)
[03/06/2022, 22:02:59 ERROR] (unknown):     at _allCode (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:101:8)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Object.<anonymous> (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\index.js:33:1)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Module.load (internal/modules/cjs/loader.js:950:32)
[03/06/2022, 22:02:59 ERROR] (unknown):     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[03/06/2022, 22:02:59 ERROR] (unknown): 
[03/06/2022, 23:08:37 ERROR] (unknown): Uncaught Exception (process.on handle) ReferenceError: path is not defined
[03/06/2022, 23:08:37 ERROR] (unknown):     at Object.test (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\jarvis.js:176:35)
[03/06/2022, 23:08:37 ERROR] (unknown):     at Object.function (C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\windowsTrayMenu.js:26:26)
[03/06/2022, 23:08:37 ERROR] (unknown):     at C:\Users\Sylicium\Documents\devlopement\Cle USB de dev\#41 Jarvis\V4\V4.1\localModules\windowsTrayMenu.js:80:50
[03/06/2022, 23:08:37 ERROR] (unknown): 
